name: Tests
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.2
      - uses: actions/checkout@v1
      - name: Test
        run: make test
      - name: Update coverage report
        uses: ncruces/go-coverage-report@main

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.2
        id: go
      - uses: actions/checkout@v1
      - name: Benchmark
        run: make bench
